# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Polygot"
  config.vm.network :forwarded_port, guest: 6379, host: 6379 
  config.vm.network :forwarded_port, guest: 5984, host: 5984 
  config.vm.network :forwarded_port, guest: 7474, host: 7474
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.provision :shell, :path => "provision.sh"
end
