# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.network :forwarded_port, guest: 6379, host: 6379 

  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
end
